services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/web/staticfiles/
    ports:
      - 80:80
    depends_on:
      - app

  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    env_file:
      - ./config/.env.app
    volumes:
      - static_volume:/app/web/staticfiles/
    depends_on:
      - redis
      - db
    ports:
      - 5000:5000


  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/.env.db
    expose:
      - 5432


  redis:
    image: redis:7.0.1
    env_file:
      - ./config/.env.app
    expose:
      - 6379


volumes:
  static_volume:
  postgres_data:
